### ISSUE TITLE
Close connections in sqlalchemy/postgres.

### ISSUE THREAD

**Issue by fantom0005** [Relrin/aiorest-ws#79]
Posgres default have 100 max connections. With new request started new connection. But connection not closing after request and number of connections is accumulating.
Fix this bug, please.

**Comment by Relrin** [comment]
Hi, @fantom0005!

Thanks for an issue. Before I'll start to fix codebase of aiorest-ws library, I'd like to know about the consequences, that leads to this situation:
Are you sure that your application works properly with the SQLAlchemy sessions/connections? You should call `close()` method after using for the opened [session](http://docs.sqlalchemy.org/en/latest/orm/session.html) or [connection](http://docs.sqlalchemy.org/en/latest/core/connections.html) object. Otherwise it leads to connection leaks.
If your codebase is fine and doesn't have this kind of programmer errors, then could you provide a couple snippets of code (if it possible) with views and serializers where you've got this issue? It slightly help me to find an error in code.

**Comment by fantom0005** [comment]
Sorry, I was wrong.
